### ISSUE TITLE
Make image FROM `alpine:edge` instead of `php:7.1-alpine`

### ISSUE THREAD

**Issue by Fuco1** [phpstan/docker-image#11]
The official php image seems to use really intricate way to install php.  Recently on alpine edge there are packages for php and extensions which allow very very simple extension installation.  It is basically the same as on `apt`:

    RUN apk add php7 php7-json php7-mongodb php7-phar php7-mbstring php7-iconv php7-openssl php7-tokenizer php7-pdo

Right now the images in this repo are "unusable" for a project which uses extensions such as mongodb as it is incredibly difficult to install those extensions.

Also it is very difficult to use phpstan in this way as an "interactive" checker inside other tools.  For example there are vim/emacs plugins which pass "the current file" as an argument, but because we mount into `/app` the paths differ and things break.

Also installing phpstan extensions seems impossible or at least I couldn't get it working.  I'm talking about `phpstan/phpstan-doctrine` and similar.

So I ended up with my own dockerfile:

```
FROM alpine:edge

# PHP
RUN echo 'http://alpine.gliderlabs.com/alpine/edge/community' >> /etc/apk/repositories
RUN echo 'http://alpine.gliderlabs.com/alpine/edge/testing' >> /etc/apk/repositories
RUN apk update
RUN apk add curl openssl git tini
RUN apk add php7 php7-json php7-mongodb php7-phar php7-mbstring php7-iconv php7-openssl php7-tokenizer php7-pdo php7-session

RUN echo "memory_limit=-1" > /etc/php7/conf.d/memory-limit.ini

# COMPOSER
ENV COMPOSER_HOME /composer
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
  && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
  && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { echo 'Invalid installer' . PHP_EOL; exit(1); }" \
  && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer \
  && php -r "unlink('/tmp/composer-setup.php');" \
  && php -r "unlink('/tmp/composer-setup.sig');"

ENV PATH /composer/vendor/bin:$PATH

# PHPSTAN
ENV PHPSTAN_VERSION 0.8.x

RUN composer global require phpstan/phpstan ^0.8
RUN composer global require phpstan/phpstan-doctrine ^0.8
RUN composer global require phpstan/phpstan-nette ^0.8
RUN composer global show | grep phpstan

ENTRYPOINT ["/sbin/tini", "--", "phpstan"]
```

This can be easily extended with extra extensions for either php or phpstan.  The invocation is a bit more involved but can be wrapped with a shellscript/function

    docker run -w $PWD -v $PWD:$PWD --rm saleschamp/phpstan analyze -c $PWD/app/config/phpstan.neon --level=7 -a /composer/vendor/autoload.php app

**Comment by tommy-muehle** [comment]
Sorry for the late response. I totally agree with you. I only think about the repositorie's we can use.
I would prefer "http://dl-cdn.alpinelinux.org/alpine/edge/community". Because it's an official one.

**Comment by tommy-muehle** [comment]
I updated all Dockerfile's today. Now they extend the official Alpine Docker image and install PHP via APK. Thanks for this suggestion!

**Comment by Fuco1** [comment]
Awesome!  Thanks for the heads up.
