### ISSUE TITLE
0.9 image

### ISSUE THREAD

**Issue by greg0ire** [phpstan/docker-image#16]
Hello, is there going to be a specific image for 0.9, or are we supposed to use the experimental image for this?

**Comment by tommy-muehle** [comment]
Hi @greg0ire, thanks for your suggestion. I'll create a new Docker tag for version 0.9 today.

**Comment by greg0ire** [comment]
Thanks!

**Comment by tommy-muehle** [comment]
No problem. Please feel also free to contact me if you have any problems. Because I also switched internally from the [Alpine PHP Docker-Image](https://github.com/docker-library/php/tree/1a00d92ff469906a4b46f2646d5dfea29ea129f1/7.1/alpine3.4/cli) to the normal Alpine Docker-Image with PHP via APK.

**Comment by greg0ire** [comment]
No issues at first glance, will keep you posted if I get any issues.
