### ISSUE TITLE
Upgrade to PHP version 7.2

### ISSUE THREAD

**Issue by KoenvanWijnen** [phpstan/docker-image#22]
Are there plans to upgrade the PHP version in the Docker image to PHP7.2?

Because i now get errors if i want to analyse PHP7.2 code via the Docker image.

For example i get:
```
PHP Warning:  Uncaught PHPStan\Broker\ClassAutoloadingException: Class *\*\object not found and could not be autoloaded. in /app/vendor/phpstan/phpstan/src/Broker/Broker.php:345
Stack trace:
#0 [internal function]: PHPStan\Broker\Broker->PHPStan\Broker\{closure}('*...')
#1 /app/src/*.php(14): spl_autoload_call('*...')
#2 /app/vendor/composer/ClassLoader.php(444): include('/app/src/*...')
#3 /app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/app/vendor/com...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('*...')
#5 [internal function]: spl_autoload_call('*...')
#6 /app/vendor/phpstan/phpstan/src/Broker/Broker.php(350): class_exists('*...')
#7 /app/vendor/phpstan/phpstan/src/Broker/Broker.php(241): PHPStan\Broker\Broker->hasClass('*...')
#8 /app/vendor/phpstan/phpstan/src/Analyser/NodeScopeRe in /app/vendor/phpstan/phpstan/src/Broker/Broker.php on line 345
PHP Fatal error:  Declaration of *::*(*\object $data, string $key = self::*): void must be compatible with *::save(*\object $data, string $key): void in /app/src/*.php on line 14
```

**Comment by ondrejmirtes** [comment]
Hi, this is weird, it should work the same. Can you show the code it analyses?

**Comment by KoenvanWijnen** [comment]
I made an example so u can reproduce the error.
https://github.com/KoenvanWijnen/phpstan-example

`docker run --rm -v /path/to/code:/app phpstan/phpstan analyse src`

**Comment by ondrejmirtes** [comment]
I understand now - PHP cannot load the classes because it interprets `object` differently and think the methods are incompatible.

cc @tommy-muehle can we switch to 7.2? I think there's no harm in it.

**Comment by tommy-muehle** [comment]
Sorry for the late response.

@ondrejmirtes 
Can we upgrade all images to PHP 7.2? I mean for all PHPStan versions from 0.6 to 0.10?
Or would you prefer this change only to the newest versions?

**Comment by ondrejmirtes** [comment]
Hi @tommy-muehle, only for 0.10, we shouldn't touch the older ones :) (PHP 7.2 didn't even exist when some of them were released and they're not tested with it.)

**Comment by tommy-muehle** [comment]
Hi @ondrejmirtes, thanks. I'll do it now.

**Comment by KoenvanWijnen** [comment]
@ondrejmirtes and @tommy-muehle thank you for your help!
