### ISSUE TITLE
[CONF] Extensions configuration | Docker & Composer

### ISSUE THREAD

**Issue by Guikingone** [phpstan/docker-image#28]
Hi everyone, what's up? 

Small question about installing global phpstan extensions (like Doctrine, Symfony, etc), when using the image, I try to install the extensions globally: 

```Dockerfile
FROM phpstan/phpstan

RUN composer global require phpstan/phpstan-phpunit phpstan/phpstan-doctrine phpstan/phpstan-symfony
```

Problem is, when using this new image, I want that phpstan use the installed extensions, is there any way to tell it to use it ? 

Here's the phpstan.neon file:

```neon
includes:
	- vendor/phpstan/phpstan-doctrine/extension.neon
	- vendor/phpstan/phpstan-symfony/extension.neon
	- vendor/phpstan/phpstan-phpunit/extension.neon
parameters:
    symfony:
        container_xml_path: %rootDir%/../../../var/cache/dev/srcDevDebugProjectContainer.xml
```

I don't really know how to tell it to use them 😞 

I've tried to tell it to use `~/.composer/vendor/...` but an error is thrown telling me that the folder doesn't exist. 

Thanks for the feedback.

**Comment by ondrejmirtes** [comment]
I think you need to look for them under `/composer`.

For example:

```
- /composer/vendor/phpstan/phpstan-doctrine/extension.neon
```

**Comment by Guikingone** [comment]
Ok, just fixed the file thanks to your precision: 

```neon
includes:
	- /composer/vendor/phpstan/phpstan-doctrine/extension.neon
	- /composer/vendor/phpstan/phpstan-symfony/extension.neon
	- /composer/vendor/phpstan/phpstan-phpunit/extension.neon
parameters:
    symfony:
        container_xml_path: %currentWorkingDirectory%/var/cache/dev/appDevDebugProjectContainer.xml
```

Works pretty good, thanks for the fast feedback :)

Maybe it could a good idea to update the current documentation in order to explain this point? 🤔

**Comment by ondrejmirtes** [comment]
Feel free to send a PR with the README updated :)
