### ISSUE TITLE
Check PHAR file instead of global PHPStan (Composer) installation

### ISSUE THREAD

**Issue by tommy-muehle** [phpstan/docker-image#5]
Since the 0.7 release of PHPStan an experimental PHAR file exist. So we need to check this against the global PHPStan installation via Composer.

**Comment by wiese** [comment]
I do agree that phar should become the default vehicle to install (taking composer out of the equation). Once this step is done, versioning has to be picked up again for the phar-installed images.

**Comment by ondrejmirtes** [comment]
Composer cannot be taken out of the equation because of support for PHPStan extensions.

**Comment by ondrejmirtes** [comment]
I started using the PHAR version in all Docker images :)
