### ISSUE TITLE
please add imap extension to docker image

### ISSUE THREAD

**Issue by glensc** [phpstan/docker-image#6]
please add imap extension to docker image,

or class that mocks the interfaces?
perhaps https://github.com/JetBrains/phpstorm-stubs/ ?

```
 ------ ----------------------------------------- 
  Line   Mail/ImapMessage.php                     
 ------ ----------------------------------------- 
  62     Function imap_fetch_overview not found.  
  64     Function imap_fetchheader not found.     
  65     Function imap_body not found.            
  87     Function imap_headerinfo not found.      
  128    Function imap_delete not found.          
  131    Function imap_setflag_full not found.  
```

**Comment by tommy-muehle** [comment]
Hi @glensc,
please take a look at the [customizing part](https://github.com/phpstan/docker-image#customizing) on the README.

So your own Dockerfile can look like this:
```
FROM phpstan/phpstan:latest
RUN apk add --no-cache --virtual .persistent-deps imap-dev openssl-dev \
    && apk add --no-cache --virtual .build-deps autoconf gcc make g++ zlib-dev file libc-dev pkgconf \
    && docker-php-ext-configure imap --with-imap --with-imap-ssl \
    && docker-php-ext-install imap \
    && apk del .build-deps
```

Hope that helps you.

**Comment by glensc** [comment]
but including stubs in the image is not that bad idea, the extensions do not need to be real, i.e being executed, do they?

**Comment by tommy-muehle** [comment]
@glensc 
You're totally right. Sorry I didn't read your comment correctly. I will check this via an extra issue.
And thanks a lot for this improvement idea.

**Comment by glensc** [comment]
@tommy-muehle don't forget to update here, so i can subscribe "there". thanks! and thanks for revisiting this issue.
