### ISSUE TITLE
Add stubs for PHP extensions

### ISSUE THREAD

**Issue by tommy-muehle** [phpstan/docker-image#7]
@glensc had the great idea to add stubs (for example https://github.com/JetBrains/phpstorm-stubs/) to this image to run PHPStan over code where otherwise additional PHP extensions (like intl, imap, soap, ...) would be necessary.

**Comment by tommy-muehle** [comment]
@ondrejmirtes 
Did you know or see some disadvantages?

**Comment by ondrejmirtes** [comment]
@tommy-muehle I see a problem with those stubs getting out of date or being for the wrong PHP version. Current advantage of PHPStan is that it uses native PHP reflection so this information is always up to date (albeit we found out that PHP reflection itself contains bugs, it's not that bad as when we'd use static and possibly out of date stubs)...

**Comment by tommy-muehle** [comment]
Yes, out-of-date stubs could be a problem. But for example Jetbrains stubs are greatly up to date. [But they provide no autoloading](https://github.com/JetBrains/phpstorm-stubs/blob/master/composer.json). So this is here the show stopper.

So I will close the issue. If someone will provide a solution we can reopen it.
