### ISSUE TITLE
Make "latest" track phpstan's releases (not master)

### ISSUE THREAD

**Issue by wiese** [phpstan/docker-image#8]
Add an additional _stable_ tag, that tracks https://github.com/phpstan/phpstan/releases/latest, or - preferably - change _latest_ to do so, [instead of **dev-master**](https://github.com/phpstan/docker-image/blob/master/latest/Dockerfile#L6) which feels dangerous and should not really be the default.

As a point of reference: The guys at https://hub.docker.com/_/php/ make it sound a bit like _latest_ is bleeding edge, while [in fact](https://github.com/docker-library/php/blob/76a1c5ca161f1ed6aafb2c2d26f83ec17360bc68/7.1/Dockerfile#L50) they do reference a concrete tag.

**Comment by tommy-muehle** [comment]
Sounds for me like a definition question. 

The version tag's "0.6" and "0.7" and all other in the future are always point to the _latest_ and _stable_ version in this release branch. So you can use one of this tag's instead of latest.
But I see no reason to add a further tag "stable".

**Comment by wiese** [comment]
Thanks for taking the time to respond.
To clarify my point, _latest_ should point to a stable version, and not what is akin to a nightly build.
But sure, I can (and will have to) use a numeric tag.
